export const REQUEST_DETAIL = "요청상세";
export const REQUEST_INFO = "Request info.";
export const REQUEST_NUMBER_TEXT = "요청번호";
export const USER_CAR_TYPE = "고객차종";
export const USER_CAR_NUMBER = "차량번호";
export const USER_PHONE_NUMBER = "고객 연락처";
export const USER_LOCATION = "이용지역";
export const REQUEST_DATE = "요청일";
export const ADDITIONAL_REQUESTS = "추가 요청사항";
